logging:
  file:
    name: cx-flow.log

cx-flow:
  bug-tracker: Sarif
  bug-tracker-impl:
    - CxXml
    - Json
    - GitHub
    - Csv
    - Sarif
  filter-severity:
    - High
    - Medium
    - Low
  mitre-url: https://cwe.mitre.org/data/definitions/%s.html
  zip-exclude: ""
  break-build: false
  enabled-vulnerability-scanners:
    #- sca
    - sast
  
checkmarx:
  base-url: https://api.checkmarx.net
  portal-url: https://cloud.checkmarx.net
  # CxOD Business unit that will contain the project/application/scan
  team: \Demo\CxFlow
  url: ${checkmarx.base-url}
  multi-tenant: true
  configuration: Default Configuration
  #
  ## Available Scan defaults
  #
  #   - CXOD_MOBILE_NATIVE = 1;
  #   - CXOD_MOBILE_WEB_BASED = 2;
  #   - CXOD_DESKTOP_NATIVE = 3;
  #   - CXOD_DESKTOP_WEB = 4;
  #   - CXOD_API = 5;
  #   - CXOD_FRONTEND = 6;
  #   - CXOD_BACKEND = 7;
  #   - CXOD_LAMBDA = 8;
  #   - CXOD_CLI = 9;
  #   - CXOD_SERVICE = 10;
  #   - CXOD_SMART_DEVICE = 11;
  #   - CXOD_OTHER = 12;
  scan-preset: 1,2,3,4,5,9

github:
  url: https://github.com
  api-url: https://api.github.com/repos/
  block-merge: true
  error-merge: true

jira:
  
json:
  file-name-format: "cx.json"
  data-folder: "/tmp"

cx-xml:
  file-name-format: "cx.xml"
  data-folder: "/tmp"

csv:
  file-name-format: "cx.csv"
  data-folder: "/tmp"
  include-header: true
  fields:
    - header: Application
      name: application
      default-value: unknown
    - header: file
      name: filename
    - header: Vulnerability Name
      name: category
    - header: CWE
      name: cwe
    - header: Severity
      name: severity
    - header: Similarity ID
      name: similarity-id
